### ISSUE TITLE
Panic when generating RSS/atom feed

### ISSUE THREAD

**Issue by proycon** [getzola/zola#1279]
# Bug Report

## Environment

Zola version: v0.12.2  (and also v0.13 as in the current ``next`` branch)

## Expected Behavior

I expect an RSS feed to be generated. My site builds fine when ``generate_feed = false``.

## Current Behavior

As soon as ``generated_feed`` is enabled. The build panics (traceback is from the ``next`` branch):

```
Building site...
`highlight_code` has been moved to a [markdown] section. Top level `highlight_code` and `highlight_theme` will stop working in 0.14.
-> Creating 49 pages (0 orphan), 2 sections, and processing 169 images
thread 'main' panicked at 'a Display implementation returned an error unexpectedly: Error', /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/liballoc/string.rs:2165:9
stack backtrace:
   0:     0x562509cd0ca4 - backtrace::backtrace::libunwind::trace::h5ae3454ebe40b621
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1:     0x562509cd0ca4 - backtrace::backtrace::trace_unsynchronized::hbf6f267a483fb2c0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2:     0x562509cd0ca4 - std::sys_common::backtrace::_print_fmt::h37755015d94b9085
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x562509cd0ca4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0561c8cd3569b40d
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x562509cfb00c - core::fmt::write::h86a597a35d48a212
                               at src/libcore/fmt/mod.rs:1063
   5:     0x562509cc8343 - std::io::Write::write_fmt::h73d9dc0f29eefe48
                               at src/libstd/io/mod.rs:1426
   6:     0x562509cd3ab5 - std::sys_common::backtrace::_print::h6c60c5ee09af0233
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x562509cd3ab5 - std::sys_common::backtrace::print::hf9d1db01634f9b2a
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x562509cd3ab5 - std::panicking::default_hook::{{closure}}::h1db9298dd213ae95
                               at src/libstd/panicking.rs:204
   9:     0x562509cd3802 - std::panicking::default_hook::h3272faf6cc91fd2e
                               at src/libstd/panicking.rs:224
  10:     0x562509cd4112 - std::panicking::rust_panic_with_hook::hb976084785e50594
                               at src/libstd/panicking.rs:470
  11:     0x562509cd3cfb - rust_begin_unwind
                               at src/libstd/panicking.rs:378
  12:     0x562509cf8db1 - core::panicking::panic_fmt::h45f7d6868edb5678
                               at src/libcore/panicking.rs:85
  13:     0x562509cf8bd3 - core::option::expect_none_failed::hd7ba247f271405e7
                               at src/libcore/option.rs:1211
  14:     0x562509c7734a - core::result::Result<T,E>::expect::h36bf8df2d5d6fa22
                               at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libcore/result.rs:961
  15:     0x56250976a69c - <T as alloc::string::ToString>::to_string::hcd2cf8832d479bf8
                               at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/liballoc/string.rs:2165
  16:     0x56250979a212 - tera::builtins::filters::common::date::h67395916db68a5f6
                               at /home/proycon/.cargo/registry/src/github.com-1ecc6299db9ec823/tera-1.5.0/src/builtins/filters/common.rs:140
  17:     0x5625097d42da - core::ops::function::Fn::call::hd79546f105919d08
                               at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libcore/ops/function.rs:72
  18:     0x56250979a6f1 - <F as tera::builtins::filters::Filter>::filter::ha0c80810214ce721
                               at /home/proycon/.cargo/registry/src/github.com-1ecc6299db9ec823/tera-1.5.0/src/builtins/filters/mod.rs:28
  19:     0x562509832c6f - tera::renderer::processor::Processor::eval_filter::ha8d98c868133aa6a
                               at /home/proycon/.cargo/registry/src/github.com-1ecc6299db9ec823/tera-1.5.0/src/renderer/processor.rs:560
  20:     0x56250982f1b4 - tera::renderer::processor::Processor::eval_expression::hce24ccf4b72b443e
                               at /home/proycon/.cargo/registry/src/github.com-1ecc6299db9ec823/tera-1.5.0/src/renderer/processor.rs:418
  21:     0x56250983a08b - tera::renderer::processor::Processor::render_node::h3d1ef30f12be6ade
                               at /home/proycon/.cargo/registry/src/github.com-1ecc6299db9ec823/tera-1.5.0/src/renderer/processor.rs:940
  22:     0x562509829bfd - tera::renderer::processor::Processor::render_body::hcb4f856fb27dcf56
                               at /home/proycon/.cargo/registry/src/github.com-1ecc6299db9ec823/tera-1.5.0/src/renderer/processor.rs:152
  23:     0x56250982b03b - tera::renderer::processor::Processor::render_for_loop::h4e7eda1578e6143e
                               at /home/proycon/.cargo/registry/src/github.com-1ecc6299db9ec823/tera-1.5.0/src/renderer/processor.rs:224
  24:     0x56250983ac2e - tera::renderer::processor::Processor::render_node::h3d1ef30f12be6ade
                               at /home/proycon/.cargo/registry/src/github.com-1ecc6299db9ec823/tera-1.5.0/src/renderer/processor.rs:954
  25:     0x56250983c7ac - tera::renderer::processor::Processor::render::h469350ae1ebf25a3
                               at /home/proycon/.cargo/registry/src/github.com-1ecc6299db9ec823/tera-1.5.0/src/renderer/processor.rs:1029
  26:     0x56250989076c - tera::renderer::Renderer::render::h7e1521fe097f8e2e
                               at /home/proycon/.cargo/registry/src/github.com-1ecc6299db9ec823/tera-1.5.0/src/renderer/mod.rs:53
  27:     0x562509761a4b - tera::tera::Tera::render::hca8093ab8009d68f
                               at /home/proycon/.cargo/registry/src/github.com-1ecc6299db9ec823/tera-1.5.0/src/tera.rs:309
  28:     0x5625090bef60 - utils::templates::render_template::h0f2bc095741cfc7b
                               at components/utils/src/templates.rs:44
  29:     0x562507ef060c - site::feed::render_feed::h2eed8d0b41008fc0
                               at components/site/src/feed.rs:76
  30:     0x562507eccb81 - site::Site::render_feed::h4dd83c62f5c8ff68
                               at components/site/src/lib.rs:938
  31:     0x562507e87dd5 - site::Site::build::h4e4dc27ea44740bb
                               at components/site/src/lib.rs:681
  32:     0x562507c8eba0 - zola::cmd::build::build::h117774ea1af97e7e
                               at src/cmd/build.rs:28
  33:     0x562507c2027c - zola::main::hc83ff2659f42bcc2
                               at src/main.rs:41
  34:     0x562507d81e0b - std::rt::lang_start::{{closure}}::hfeda95dc51ed54c9
                               at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libstd/rt.rs:67
  35:     0x562509cd3bd3 - std::rt::lang_start_internal::{{closure}}::hc0a1280e68ffc5da
                               at src/libstd/rt.rs:52
  36:     0x562509cd3bd3 - std::panicking::try::do_call::h1d43a4d29f303ef5
                               at src/libstd/panicking.rs:303
  37:     0x562509cddf97 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  38:     0x562509cd46fc - std::panicking::try::h5ef738612ab0072d
                               at src/libstd/panicking.rs:281
  39:     0x562509cd46fc - std::panic::catch_unwind::h1df9a04c7f1c6fc3
                               at src/libstd/panic.rs:394
  40:     0x562509cd46fc - std::rt::lang_start_internal::h97d4af4643f4b0e4
                               at src/libstd/rt.rs:51
  41:     0x562507d81de7 - std::rt::lang_start::h4ebdc910722314d9
                               at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libstd/rt.rs:67
  42:     0x562507c20eca - main
  43:     0x7f768aa1e152 - __libc_start_main
  44:     0x562507c1b7ae - _start
  45:                0x0 - <unknown>
```

I have ``feed_filename ="rss.xml"``, but the same happens if I opt for ``atom.xml``.

## Step to reproduce

Run ``zola build`` on a clone of the ``zola`` branch of https://github.com/proycon/homepage after ensuring ``generate_feed = true`` in ``config.toml``.

(see https://github.com/proycon/homepage/tree/zola)

**Comment by Keats** [comment]
Ah chrono panicking :/ It looks like the `%+` formatting of the atom.xml clashes with some of the dates in your blog. Changing the format to `%F` works so it's something to do with timezones probably. I'll try to reproduce it in Tera directly.

**Comment by proycon** [comment]
Right, and in ``rss.xml`` it works if I remove ``%z`` (hopefully I'm not violating any rss spec if I do that).

I also tried to remove the explicit timezone information from my posts (I don't care much about preserving them anyway), but that didn't help.

**Comment by Keats** [comment]
The issue is with dates like `2017-01-01T00:00:00`. I reproduced the issue in a test in Tera and fixed it there: https://github.com/Keats/tera/pull/589/files#diff-c5b44f990094adbc8f3232c3ac9f474ff53dc13167e76b39f7c9f687629ae9cb
Looks like we just need to assume UTC when there are no offsets, otherwise it can panic :/
