### ISSUE TITLE
internal error: entered unreachable code: Got a change in an unexpected path: `/config.toml`

### ISSUE THREAD

**Issue by Luro02** [getzola/zola#1602]
# Bug Report

## Environment

Zola version: `0.14.1`

Windows

## Expected Behavior

Should not have reached the unreachable statement:
https://github.com/getzola/zola/blob/3dcc080f9d3558e9f811b442ebe09699f363f930/src/cmd/serve.rs#L667

## Current Behavior
Changing something in the `config.toml` file crashes `zola serve`:

```
Change detected @ 2021-08-27 22:29:37
thread 'main' panicked at 'internal error: entered unreachable code: Got a change in an unexpected path: /config.toml', src\cmd\serve.rs:667:9
stack backtrace:
   0:     0x7ff67225ed5e - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/574d37568029f5c637557a87426ade54770d9a14\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff67225ed5e - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/574d37568029f5c637557a87426ade54770d9a14\/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff67225ed5e - std::sys_common::backtrace::_print_fmt
                               at /rustc/574d37568029f5c637557a87426ade54770d9a14\/library\std\src\sys_common\backtrace.rs:67
   3:     0x7ff67225ed5e - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/574d37568029f5c637557a87426ade54770d9a14\/library\std\src\sys_common\backtrace.rs:46
   4:     0x7ff672278a6a - core::fmt::write
                               at /rustc/574d37568029f5c637557a87426ade54770d9a14\/library\core\src\fmt\mod.rs:1117
   5:     0x7ff672256d78 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/574d37568029f5c637557a87426ade54770d9a14\/library\std\src\io\mod.rs:1667
   6:     0x7ff672261946 - std::sys_common::backtrace::_print
                               at /rustc/574d37568029f5c637557a87426ade54770d9a14\/library\std\src\sys_common\backtrace.rs:49
   7:     0x7ff672261946 - std::sys_common::backtrace::print
                               at /rustc/574d37568029f5c637557a87426ade54770d9a14\/library\std\src\sys_common\backtrace.rs:36
   8:     0x7ff672261946 - std::panicking::default_hook::closure$1
                               at /rustc/574d37568029f5c637557a87426ade54770d9a14\/library\std\src\panicking.rs:210
   9:     0x7ff672261429 - std::panicking::default_hook
                               at /rustc/574d37568029f5c637557a87426ade54770d9a14\/library\std\src\panicking.rs:227
  10:     0x7ff672261fa5 - std::panicking::rust_panic_with_hook
                               at /rustc/574d37568029f5c637557a87426ade54770d9a14\/library\std\src\panicking.rs:624
  11:     0x7ff672261b91 - std::panicking::begin_panic_handler::closure$0
                               at /rustc/574d37568029f5c637557a87426ade54770d9a14\/library\std\src\panicking.rs:521
  12:     0x7ff67225f6bf - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure$0,never$>
                               at /rustc/574d37568029f5c637557a87426ade54770d9a14\/library\std\src\sys_common\backtrace.rs:141
  13:     0x7ff672261ae9 - std::panicking::begin_panic_handler
                               at /rustc/574d37568029f5c637557a87426ade54770d9a14\/library\std\src\panicking.rs:517
  14:     0x7ff672499180 - core::panicking::panic_fmt
                               at /rustc/574d37568029f5c637557a87426ade54770d9a14\/library\core\src\panicking.rs:93
  15:     0x7ff670ae7fbe - zola::cmd::serve::serve::h6f365ad17bac3720
  16:     0x7ff670ae591c - zola::cmd::serve::serve::h6f365ad17bac3720
  17:     0x7ff670a46640 - tokio::fs::metadata::metadata::{{closure}}::{{closure}}::h0fc482792f87e3e0
  18:     0x7ff670a3cb06 - core::ops::function::FnOnce::call_once::hdbd9c2e71b7d7a81
  19:     0x7ff670adda27 - std::sys_common::backtrace::__rust_begin_short_backtrace::h1e35ee89025f36e7
  20:     0x7ff670a7f07c - std::rt::lang_start::{{closure}}::ha9e502691b3de94e
  21:     0x7ff672262506 - core::ops::function::impls::impl$2::call_once
                               at /rustc/574d37568029f5c637557a87426ade54770d9a14\library\core\src\ops\function.rs:259
  22:     0x7ff672262506 - std::panicking::try::do_call
                               at /rustc/574d37568029f5c637557a87426ade54770d9a14\/library\std\src\panicking.rs:403
  23:     0x7ff672262506 - std::panicking::try
                               at /rustc/574d37568029f5c637557a87426ade54770d9a14\/library\std\src\panicking.rs:367
  24:     0x7ff672262506 - std::panic::catch_unwind
                               at /rustc/574d37568029f5c637557a87426ade54770d9a14\/library\std\src\panic.rs:129
  25:     0x7ff672262506 - std::rt::lang_start_internal::closure$2
                               at /rustc/574d37568029f5c637557a87426ade54770d9a14\/library\std\src\rt.rs:45
  26:     0x7ff672262506 - std::panicking::try::do_call
                               at /rustc/574d37568029f5c637557a87426ade54770d9a14\/library\std\src\panicking.rs:403
  27:     0x7ff672262506 - std::panicking::try
                               at /rustc/574d37568029f5c637557a87426ade54770d9a14\/library\std\src\panicking.rs:367
  28:     0x7ff672262506 - std::panic::catch_unwind
                               at /rustc/574d37568029f5c637557a87426ade54770d9a14\/library\std\src\panic.rs:129
  29:     0x7ff672262506 - std::rt::lang_start_internal
                               at /rustc/574d37568029f5c637557a87426ade54770d9a14\/library\std\src\rt.rs:45
  30:     0x7ff670a7f050 - std::rt::lang_start::h8766afa3e39e71c6
  31:     0x7ff670a46c06 - main
  32:     0x7ff6724960ec - invoke_main
                               at d:\a01\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  33:     0x7ff6724960ec - __scrt_common_main_seh
                               at d:\a01\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  34:     0x7ff85b417034 - BaseThreadInitThunk
  35:     0x7ff85cf42651 - RtlUserThreadStart
```

## Step to reproduce
Download this repository: [example_blog.zip](https://github.com/getzola/zola/files/7069293/example_blog.zip)

Run `zola serve` and change some value in the `config.toml` (for example, changing a `bool` from `true` to `false`)

**Comment by chris-morgan** [comment]
> Listening for changes in /home/chris/sites/chrismorgan.info{/home/chris/sites/chrismorgan.info/config.toml, content, sass, static, templates}

Looks like a simple case of accidental absolutification of a path.

**Comment by acheronfail** [comment]
@Keats this has been fixed by #1616 and can be closed. 🙂

**Comment by Keats** [comment]
Let's keep it open to avoid duplicate issues until the next release

**Comment by colorlessred** [comment]
I am running 0.14.1 and I get `internal error: entered unreachable code: Got a change in an unexpected path: /config.toml', src\cmd\serve.rs:667:9`
I am not sure if this version already contains the fix or not.

**Comment by Keats** [comment]
It doesn't contain it. You can try the `next` branch which has this fixed

**Comment by colorlessred** [comment]
Excellent, thanks.

G
