### ISSUE TITLE
panic when sorting content on date, but the date is not in the correct format.

### ISSUE THREAD

**Issue by verpeteren** [getzola/zola#216]
file: `content\blog\_index`
```
+++
title="blog section sorted by date"
sort_by = "date"
+++
...
```

file `content\blog\something\index.md`
```
+++
title="blog post with a invalid date"
date="2018_01-20"
+++
....
```

```bash
RUST_BACKTRACE=1 gutenberg serve
```

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:335:20
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:380
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:611
   5: std::panicking::begin_panic_new
             at /checkout/src/libstd/panicking.rs:553
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:521
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:497
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:92
   9: core::panicking::panic
             at /checkout/src/libcore/panicking.rs:51
  10: rayon::slice::quicksort::shift_tail
  11: rayon::slice::quicksort::recurse
  12: content::sorting::sort_pages
  13: site::Site::sort_sections_pages
  14: site::Site::populate_sections
  15: site::Site::load
  16: gutenberg::cmd::serve::serve
  17: gutenberg::main
  18: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  19: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:458
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:59
  20: __libc_start_main
  21: <unknown>
```

It would be helpfull to know, what markdown file is causing the problem (in this case 'content/blog/something/index.md').

**Comment by Keats** [comment]
I believe I fixed that yesterday, can you git pull the next branch and try
again?

**Comment by verpeteren** [comment]
Yes, there is no panic when the date is incorrect.
But be aware that in every frontmatter `date="2018-01-20"`should be changed to `date = 2018-01-20`.
