### ISSUE TITLE
Compiler errors due to old 0.9.4 version of `openssl` crate.

### ISSUE THREAD

**Issue by mitchmindtree** [getzola/zola#463]
Attempting to compile the `openssl` crate on systems with a newer version of SSL results in the following error:

```
error: failed to run custom build command for `openssl v0.9.24`                                                                                                                                                      
process didn't exit successfully: `/home/mindtree/programming/rust/gutenberg/target/release/build/openssl-73cd6a774e5ab81f/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to detect OpenSSL version', /home/mindtree/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.9.24/build.rs:16:14
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:476
   5: std::panicking::begin_panic
   6: build_script_build::main
   7: std::rt::lang_start::{{closure}}
   8: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
   9: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  10: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  11: main
  12: __libc_start_main
  13: _start
```
This can be fixed by updating to `openssl` v0.10+. Checking `cargo tree`, it looks like openssl 0.9.4 is picked up via:

```
link_checker -> reqwest -> hyper-tls -> native-tls -> openssl
```

It looks like updating the `reqwest` version depended on by `link_checker` should solve this.

sfackler/rust-openssl#987 provides a little more info on the error.

**Comment by Keats** [comment]
it's already fixed in the `next` branch

**Comment by mitchmindtree** [comment]
Ahh thanks for the quick response! I'll leave this open for you to close when you're ready in case you'd like to leave it until the `next` branch lands.

**Comment by svenstaro** [comment]
That would also be good to have in the next 0.4 release.

**Comment by Keats** [comment]
Next release is 0.5!
