### ISSUE TITLE
Parent folder containing "content" cause zola to generate wrong paths

### ISSUE THREAD

**Issue by leroycep** [getzola/zola#629]
# Bug Report

## Environment

Zola version:
```
zola 0.5.1
```

## Expected Behavior
`zola` should generate the site with `/some/content/stuff/zola-site/` as the root folder.

## Current Behavior
`zola` generates the site as if `/some/` was the root folder of the site.

If you also have a file at `/some/content/stuff/zola-site/content/_index.md`, the `zola` will crash.

```
~/p/w/c/portfolio $ exa --tree
.
├── config.toml
├── content
│  └── _index.md
├── sass
├── static
├── templates
└── themes
~/p/w/c/portfolio $ env RUST_BACKTRACE=1 zola serve
Building site...
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:345:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: rust_begin_unwind
             at src/libstd/panicking.rs:312
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::panicking::panic
             at src/libcore/panicking.rs:49
   9: library::library::Library::populate_sections
  10: site::Site::load
  11: zola::cmd::serve::create_new_site
  12: zola::cmd::serve::serve
  13: zola::main
  14: std::rt::lang_start::{{closure}}
  15: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:297
  16: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:92
  17: std::rt::lang_start_internal
             at src/libstd/panicking.rs:276
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  18: main
  19: __libc_start_main
  20: _start
             at ../sysdeps/x86_64/start.S:120
~/p/w/c/portfolio $ 
```

## Step to reproduce

```
mkdir content
cd content
zola init test
cd test

echo "<html><body>{{ page.content }}</body></html>" > templates/page.html
echo -e "+++\n+++\nHello, world!" > content/hello.md

zola serve
# Observe that you must navigate to `127.0.0.1:1111/test/content/hello` instead of `127.0.0.1:1111/hello`

echo -e "+++\n+++\n" > content/_index.md
env RUST_BACKTRACE=1 zola serve
# zola crashes
```

**Comment by Keats** [comment]
It should be fixed in the `next` branch if you want to give it a try!

**Comment by leroycep** [comment]
Indeed it does! :smile: I'm going to go ahead and close this issue now. Thanks!
