### ISSUE TITLE
Internal error: entered unreachable code: Got a change in an unexpected path (0.6)

### ISSUE THREAD

**Issue by ralfbiedert** [getzola/zola#697]
# Bug Report

I got an one-off error when working on my project:

```
D:\Development\Source\cheats.rs>zola serve
Building site...
-> Creating 0 pages (0 orphan), 0 sections, and processing 0 images
Done in 56ms.

Listening for changes in D:\Development\Source\cheats.rs\{content, config.toml, static, templates, sass}
Press Ctrl+C to stop

Web server is available at http://127.0.0.1:1111

Change detected @ 2019-05-27 08:33:19
thread 'main' panicked at 'internal error: entered unreachable code: Got a change in an unexpected path: D:\Development\Source\cheats.rs\content/_index.md', src\cmd\serve.rs:489:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

Unfortunately I can't reproduce the error with a better backtrace, but it occurred when I was switching git branches. 

I know this is an older version, so feel free to close if you think this might already be fixed. 

## Environment

Zola version: `0.6.0`
Windows 10: `1903`

**Comment by ralfbiedert** [comment]
Just happened again, this time with stack trace:

```
Change detected @ 2019-05-27 08:59:39
thread 'main' panicked at 'internal error: entered unreachable code: Got a change in an unexpected path: D:\Development\Source\cheats.rs\content/_index.md', src\cmd\serve.rs:489:9
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: onig_unicode_define_user_property
  10: BaseThreadInitThunk
  11: RtlUserThreadStart
thread '<unnamed>' panicked at '
```

The end of the last like really does stop at `

**Comment by Keats** [comment]
Ah, update to 0.7.0 this bug has been fixed already (I think)

**Comment by ralfbiedert** [comment]
Alright, thanks. I'll try with 0.7 and reopen if it happens again.
